{
 "title": "Reusable Module test",
 "description": "Start of reusable module",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display:flex; align-items:center; gap:40px;\">\n  <img src=\"https://arise-middleware.eu/wp-content/uploads/2024/03/logo-arise.png\" alt=\"ARISE\" style=\"height:80px;\">\n  <img src=\"https://www.cartif.es/wp-content/uploads/2025/08/cartiflogo-transparentbg1-1024x453.png\" alt=\"CARTIF\" style=\"height:150px;\">\n</div>\n\n<h1>General Status</h1>\n<hr>\n\n<p>General status of the module</p>"
   }
  },
  {
   "title": "Camera Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts AS time,\r\n  (compound ->> 'camera_available')::boolean AS value\r\nFROM public.attributes\r\nWHERE entityid LIKE '%stats:1'\r\nAND $__timeFilter(ts)\r\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Frames dropped",
   "type": "stat",
   "description": "Frames dropped by the camera",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "frames" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts AS time,\r\n  ((compound ->> 'frames_dropped')::integer)::int AS value\r\nFROM public.attributes\r\nWHERE entityid LIKE '%stats:1'\r\nORDER BY ts DESC"
    }
   ]
  },
  {
   "title": "Average Inference Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts AS time,\r\n  ((compound ->> 'avg_inference_ms')::float)::int AS value\r\nFROM public.attributes\r\nWHERE entityid LIKE '%stats:1'\r\nORDER BY ts DESC"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 16 },
   "options": {
    "content": "# Camera\n---\n\nRelevant information from the cameras"
   }
  },
  {
   "title": "FPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  (compound ->> 'fps_input')::float AS \"Camera\",\r\n  (compound ->> 'fps_processed')::float AS \"Processed\"\r\nFROM public.attributes\r\nWHERE entityid = 'urn:ngsi-ld:stats:1' \r\nORDER BY 1;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 14, "x": 0, "y": 26 },
   "options": {
    "content": "# Other\n---\n\nInformation relevant to actions and matches. TBD"
   }
  },
  {
   "title": "Action goals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  (compound ->> 'action_goals_received')::integer AS \"Received\",\r\n  (compound ->> 'action_goals_accepted')::integer AS \"Accepted\",\r\n  (compound ->> 'action_goals_rejected')::integer AS \"Rejected\",\r\n  (compound ->> 'action_goals_canceled')::integer AS \"Canceled\",\r\n  (compound ->> 'action_goals_succeeded')::integer AS \"Succeeded\",\r\n  (compound ->> 'action_goals_failed')::integer AS \"Failed\"\r\nFROM public.attributes\r\nWHERE entityid = 'urn:ngsi-ld:stats:1'  \r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Matches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts AS \"time\",\r\n  (compound ->> 'match_requests')::integer AS \"Requests\",\r\n  (compound ->> 'match_success')::integer AS \"Successes\",\r\n  (compound ->> 'match_fail')::integer AS \"Fails\"\r\nFROM public.attributes\r\nWHERE entityid = 'urn:ngsi-ld:stats:1'\r\nORDER BY 1;"
    }
   ]
  }
 ]
}